package bspkrs.briefcasespeakers.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

// Date: 12/14/2013 5:18:00 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

@SideOnly(Side.CLIENT)
public class ModelBriefcaseSpeakers extends ModelBase
{
    ModelRenderer suitcase;
    ModelRenderer speaker1;
    ModelRenderer speaker3;
    ModelRenderer handle3;
    ModelRenderer handle2;
    ModelRenderer handle1;
    ModelRenderer latch2;
    ModelRenderer latch1;
    
    public ModelBriefcaseSpeakers()
    {
        textureWidth = 64;
        textureHeight = 32;
        
        suitcase = new ModelRenderer(this, 0, 0);
        suitcase.addBox(0F, 0F, 0F, 14, 10, 5);
        suitcase.setTextureSize(64, 32);
        suitcase.mirror = true;
        speaker1 = new ModelRenderer(this, 38, 0);
        speaker1.addBox(0F, 0F, 0F, 5, 7, 1);
        speaker1.setTextureSize(64, 32);
        speaker1.mirror = true;
        speaker3 = new ModelRenderer(this, 38, 0);
        speaker3.addBox(0F, 0F, 0F, 5, 7, 1);
        speaker3.setTextureSize(64, 32);
        speaker3.mirror = true;
        handle3 = new ModelRenderer(this, 5, 5);
        handle3.addBox(0F, 0F, 0F, 1, 1, 1);
        handle3.setTextureSize(64, 32);
        handle3.mirror = true;
        handle2 = new ModelRenderer(this, 5, 5);
        handle2.addBox(0F, 0F, 0F, 1, 1, 1);
        handle2.setTextureSize(64, 32);
        handle2.mirror = true;
        handle1 = new ModelRenderer(this, 5, 5);
        handle1.addBox(0F, 0F, 0F, 6, 1, 1);
        handle1.setTextureSize(64, 32);
        handle1.mirror = true;
        latch2 = new ModelRenderer(this, 38, 8);
        latch2.addBox(0F, 0F, 0F, 1, 1, 2);
        latch2.setTextureSize(64, 32);
        latch2.mirror = true;
        latch1 = new ModelRenderer(this, 38, 8);
        latch1.addBox(0F, 0F, 0F, 1, 1, 2);
        latch1.setTextureSize(64, 32);
        latch1.mirror = true;
    }
    
    public void renderBriefcaseSpeakers(float f5)
    {
        suitcase.render(f5);
        speaker1.render(f5);
        speaker3.render(f5);
        handle3.render(f5);
        handle2.render(f5);
        handle1.render(f5);
        latch2.render(f5);
        latch1.render(f5);
    }
}
